-- Run once in the Supabase SQL Editor for the Wrist Mode production project.
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  session_id text not null,
  event_type text not null check (event_type in ('visit', 'product_view', 'add_to_cart', 'checkout_started', 'purchase')),
  product_id bigint references public.products(id) on delete set null,
  page text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx on public.analytics_events (created_at desc);
create index if not exists analytics_events_session_id_idx on public.analytics_events (session_id);

alter table public.analytics_events enable row level security;
