-- Wrist Mode production schema for Supabase.
-- Run this file once in the Supabase SQL Editor.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category text not null,
  brand text not null,
  name text not null,
  price numeric not null default 0,
  quantity integer not null default 0,
  description text not null default '',
  specs jsonb not null default '{}'::jsonb,
  images jsonb not null default '[]'::jsonb,
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  receipt text not null unique,
  customer jsonb not null,
  items jsonb not null,
  total numeric not null,
  payment_method text not null,
  status text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.custom_requests (
  id bigint generated by default as identity primary key,
  request_code text not null unique,
  customer jsonb not null,
  details jsonb not null,
  reference_image text,
  status text not null,
  quote_amount numeric,
  admin_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stock_alerts (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  name text not null,
  email text,
  phone text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  notified_at timestamptz
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  type text not null,
  recipient text not null,
  channel text not null,
  message text not null,
  status text not null default 'Pending',
  created_at timestamptz not null default now()
);

-- Anonymous storefront activity used for the private admin funnel.
create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  session_id text not null,
  event_type text not null check (event_type in ('visit', 'product_view', 'add_to_cart', 'checkout_started', 'purchase')),
  product_id bigint references public.products(id) on delete set null,
  page text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx on public.analytics_events (created_at desc);
create index if not exists analytics_events_session_id_idx on public.analytics_events (session_id);

-- The project is server-managed. Do not grant anonymous browser access.
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.custom_requests enable row level security;
alter table public.stock_alerts enable row level security;
alter table public.notifications enable row level security;
alter table public.analytics_events enable row level security;
